### ISSUE TITLE
Error passing several store enhancers to createStore 

### ISSUE THREAD

**Issue by vadymus** [adobe/alloy-samples#3]
Error `It looks like you are passing several store enhancers to createStore(). This is not supported. Instead, compose them together to a single function. See https://redux.js.org/tutorials/fundamentals/part-4-store#creating-a-store-with-enhancers for an example.` when loading `personalization-hybrid-spa` package. 

Steps to reproduce:
---
  - Download/clone the entire repo
  - Go to `personalization-hybrid-spa` directory
  - Run `npm install` and `npm start`
  - Load http://localhost/ and see blank screen
  - Observe error in the Console

```
app.js:6 Uncaught Error: Minified Redux error #0; visit https://redux.js.org/Errors?code=0 for the full message or use the non-minified dev environment for full errors. 
    at f (app.js:6:13067)
    at Object.<anonymous> (app.js:52:92059)
    at n (app.js:1:110)
    at Object.<anonymous> (app.js:18:33881)
    at n (app.js:1:110)
    at app.js:1:902
    at app.js:1:912
```

<img width="1188" alt="error" src="https://user-images.githubusercontent.com/5665858/196788984-1be2bdf7-1c7d-429c-afaf-96b1a31d056c.png">

**Comment by vadymus** [comment]
Error was caused by Chrome's extension `Redux DevTools` v. 3.0.11 (Redux DevTools for debugging application’s state changes.).
After disabling the extension, the app loads just fine.
